version: '3.6'

services:
  app:
    build: .
    container_name: sorinmunteanro
    hostname: sorinmunteanro
    ports:
      - "3001:3001"
    restart: on-failure

networks:
    default:
        external:
            name: sorinmunteanro
