export default {
  currentPageIndex: 0,
  pages: [
    {
      type: "welcome",
      slug: "welcome",
      color: "#ffffff",
    },
    {
      type: "company",
      backgroundColor: "#ffcc00",
      color: "#000000",
      slug: "ki-labs",
      name: "KI labs",
      url: "https://ki-labs.com/",
      start: "Feb. 2019",
      end: "today",
      title: "Programmer",
      description: [
        "KI labs is an IT consulting firm, part of KI group.",
        "Since joining, I've worked on three products:",
        "- a vehicle data enrichment and online sale-readiness assessment platform (VueJS, TypeScript, Python w/ Flask)",
        "- an online marketplace for continuing professional development programs, aimed at professionals in the healthcare industry (VueJS, TypeScript)",
        "- a cloud computing services platform (ReactJS)",
      ],
    },
    {
      type: "company",
      backgroundColor: "#57c0dc",
      color: "#ffffff",
      slug: "ottonova",
      name: "ottonova",
      url: "https://ottonova.de/",
      start: "May 2017",
      end: "Jan. 2019",
      title: "Programmer",
      description: [
        "ottonova is the first completely digital health insurance in Germany.",
        "Activity:",
        "- developing customer-facing and internal applications using Angular",
        "- building microservices using NodeJS & Express, deployed to Amazon ECS",
        "The technology stack primarily comprises TypeScript (Angular), NodeJS (Express), PHP (Symfony)",
      ],
    },
    {
      type: "company",
      backgroundColor: "#203049",
      color: "#ffffff",
      slug: "internations",
      name: "InterNations GmbH",
      url: "https://www.internations.org/",
      start: "Oct. 2013",
      end: "Apr. 2016",
      title: "Programmer",
      description: [
        "At InterNations I took part in the relaunch of their product, working in a distributed team located in Munich and Vilnius.",
        "Notable contributions include:",
        "- relaunching the product's start, user profile, forum and settings pages",
        "- normalizing the user data model, developing tooling required to migrate the existing 1.5M users to the new model",
        "- designing and implementing the API used by the web & mobile apps",
        "The technology stack comprised PHP (Symfony2, Drupal and Magento), Backbone.js, Python, RabbitMQ, Apache Solr, MySQL & Redis.",
      ],
    },
    {
      type: "company",
      backgroundColor: "#fea104",
      color: "#000000",
      slug: "honeytracks",
      name: "HoneyTracks GmbH",
      url: "https://honeytracks.com/",
      start: "Oct. 2012",
      end: "Oct. 2013",
      title: "Programmer",
      description: [
        "During my time at HoneyTracks I've worked on the company's real-time analytics solution and the various tools built around it.",
        "Most notably:",
        "- improving the in-house PHP framework and its various drivers (Memcached, beanstalkd)",
        "- introducing data fetching workers so chart data can be fetched in parallel and ahead of time",
        "The technology stack comprised PHP, Backbone.js, Beanstalkd, RabbitMQ & MySQL.",
      ],
    },
    {
      type: "company",
      backgroundColor: "#0176b0",
      color: "#ffffff",
      slug: "agilio",
      name: "Agilio Software",
      url: "https://www.agilio.eu/",
      start: "Sep. 2011",
      end: "June 2012",
      title: "Programmer",
      description: [
        "My main activity at Agilio (formerly Garessio) was developing web applications. The projects I have worked on were mostly based on the CodeIgniter and Symfony2 frameworks.",
        "Projects involved in:",
        "- Stipz, a (now defunct) video website that allowed users to (for a fee) stream video, host or attend webinars. Payment was handled using an in-house PayPal integration. (CodeIgniter, jQuery, Flash Media Server, MySQL)",
        "- Nebo Learning, an enterprise e-learning platform. (Python, Oracle Database)",
        "- Building the company's homepage. (jQuery)",
      ],
    },
    {
      type: "company",
      backgroundColor: "#6dbe5d",
      color: "#ffffff",
      slug: "arobs",
      name: "Arobs Transilvania Software",
      url: "http://www.arobs.ro/",
      start: "July 2011",
      end: "Sep. 2011",
      title: "Software Developer (Intern)",
      description: [
        "In the course of this curricular internship I worked on implementing and customizing Interactive Responsive Technology systems for pharmaceutical studies, as specified by external clients.",
        "The technology stack comprised .NET, ASP.NET Web Forms and Microsoft SQL Server 2008.",
      ],
    },
    {
      type: "company",
      backgroundColor: "#bc171d",
      color: "#ffffff",
      slug: "utcn",
      name: "Technical University of Cluj-Napoca",
      url: "http://www.utcluj.ro/en/",
      start: "Sep. 2008",
      end: "Oct. 2012",
      title: "Bachelor in Computer Science",
      description: [
        "The education provided by the Computer Science Department of the Technical University of Cluj-Napoca ensures engineering-specific training, balance between the general technical, domain fundamental and narrow specialization disciplines and the integration of both theoretical and practical aspects. This formative type of education allows graduates to easily integrate and adapt to the dynamic requests of the industry.",
        "The curriculum is based on the ACM curriculum and syllabi guidelines for computer science and engineering.",
        "Their bachelor's degree programmes are taught in either Romanian or English, folow the Bologna system and comprise 240 ECTS points, spread throughout 8 semesters.",
      ],
    },
    {
      type: "contact",
      slug: "contact",
      color: "#000000",
    },
  ],
};
